language: cpp
os: linux
group: stable

install:
 - sudo apt-get update
 - sudo apt-get install qtdeclarative5-dev qt5-default

script:
 - cd SimPlatform
 - qmake -project
 - qmake SimPlatform.pro
 - make
