language: cpp
os: linux
group: stable

install:
 - sudo aptitude install debian-keyring debian-archive-keyring
 - sudo apt-get update
 - sudo apt-get -qq install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev xbitmaps xterm libqt5svg5-dev qttools5-dev qtscript5-dev qtdeclarative5-folderlistmodel-plugin qtdeclarative5-controls-plugin -y
 
script:
 - cd SimPlatform
 - qmake -project
 - qmake SimPlatform.pro
 - make
