language: cpp
os: linux
group: stable
dist: xenial

install:
 - sudo aptitude install debian-keyring debian-archive-keyring
 - sudo apt-get update
 - sudo apt-get install build-essential g++
 - sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools
 
script:
 - echo -e "/opt/qt511/bin\n/opt/qt511/lib" > default.conf
 - sudo rm /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf
 - sudo mv default.conf /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/
 - cat /usr/lib/x86_64-linux-gnu/qtchooser/default.conf
 - cat /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf
 - cd SimPlatform
 - qmake -project "QT = core gui widgets" 
 - qmake SimPlatform.pro
 - qmake --version
 - qtchooser -l
 - make
