language: cpp
os: linux
group: stable
dist: xenial

install:
 - sudo aptitude install debian-keyring debian-archive-keyring
 - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-xenial
 - sudo apt-get update
 - sudo apt-get install build-essential g++
 - sudo apt install qt511 -meta-full
 - sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools
 - sudo apt-get install mingw-w64
 
script:
 - echo -e "/opt/qt511/bin\n/opt/qt511/lib" > default.conf
 - sudo rm /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf
 - sudo mv default.conf /usr/lib/x86_64-linux-gnu/qtchooser/
 - cd SimPlatform
 - qmake -project "QT += core gui widgets" 
 - qmake SimPlatform.pro
 - make
 - cd ../Prototype01
 - qmake -project "QT += core widgets" 
 - qmake Prototype01.pro
 - make
