language: cpp
os: linux
group: stable

install:
 - sudo aptitude install debian-keyring debian-archive-keyring
 - sudo apt-get update
 - sudo apt-get install build-essential g++
 - sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools
 
script:
 - cd SimPlatform
 - qmake -project "QT = core gui widgets" 
 - qmake SimPlatform.pro
 - qmake --version
 - make
