language: cpp
os: linux
group: stable

install:
 - sudo aptitude install debian-keyring debian-archive-keyring
 - sudo apt-get update
 - sudo apt-get install qtbase5-dev qt5-default

script:
 - cd SimPlatform
 - qmake -project
 - qmake SimPlatform.pro
 - make
