language: cpp
os: linux
group: stable
dist: bionic

install:
 - sudo aptitude install debian-keyring debian-archive-keyring
 - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.3-bionic
 - sudo apt-get update
 - sudo apt-get install build-essential g++
 - sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools
 - sudo apt install qt511-meta-full
 
script:
 - cd SimPlatform
 - qmake -project "QT = core gui widgets" 
 - qmake SimPlatform.pro
 - qmake --version
 - qtchooser -l
 - make
